using System.Windows;
using System.Windows.Controls;
using PersonalLife.Core;
namespace PersonalLife.App;
public partial class MainWindow
{
 void RenderFitness()
 {
  var data=store.ReadAll();var w=data.Workouts.SingleOrDefault(x=>x.Date==SelectedDate);
  if(w==null){var empty=Ui.Card(PageContent,"今日训练");empty.Children.Add(Ui.Text("尚未安排训练或休息日"));empty.Children.Add(Ui.Button("＋ 安排训练",()=>EditWorkout(new Workout{Date=SelectedDate})));}
  else {var top=Ui.Card(PageContent,w.IsRestDay?"今天休息":w.Title);top.Children.Add(Ui.Text($"{w.StartTime?.ToString("HH:mm")??"未指定时间"} · 预计 {w.PlannedMinutes?.ToString()??"—"} 分钟"));var buttons=Ui.Row(top);buttons.Children.Add(Ui.Button("编辑安排",()=>EditWorkout(w)));buttons.Children.Add(Ui.Button("删除训练",()=>Run(()=>undo.Delete<Workout>(w.Id))));if(!w.IsRestDay){Ui.Check(top,"训练已完成",w.IsCompleted,v=>Run(()=>new FitnessService(store).Save(w with{IsCompleted=v})));buttons.Children.Add(Ui.Button("＋ 添加动作",()=>EditExercise(new Exercise{WorkoutId=w.Id,SortOrder=data.Exercises.Count(x=>x.WorkoutId==w.Id)})));}
   foreach(var e in data.Exercises.Where(x=>x.WorkoutId==w.Id).OrderBy(x=>x.SortOrder)){var c=Ui.Card(PageContent,e.Name);c.Children.Add(Ui.Text(e.Kind=="strength"?$"计划 {e.PlannedSets} 组 × {e.PlannedReps} 次 · {e.PlannedWeightKg?.ToString()??"自重"} kg":$"计划 {e.PlannedMinutes} 分钟 · 实际 {e.ActualMinutes?.ToString()??"未记录"} 分钟"));Ui.Check(c,"动作已完成",e.IsCompleted,v=>Run(()=>new FitnessService(store).Save(e with{IsCompleted=v})));var row=Ui.Row(c);row.Children.Add(Ui.Button("编辑动作 / 时长",()=>EditExercise(e)));row.Children.Add(Ui.Button("删除动作",()=>Run(()=>undo.Delete<Exercise>(e.Id))));if(e.Kind=="strength"){foreach(var set in data.ExerciseSets.Where(x=>x.ExerciseId==e.Id).OrderBy(x=>x.SetNumber)){var r=Ui.Row(c);r.Children.Add(Ui.Text($"第 {set.SetNumber} 组　{set.ActualReps} 次　{set.ActualWeightKg?.ToString()??"—"} kg"));r.Children.Add(Ui.Button("修改",()=>EditSet(set)));r.Children.Add(Ui.Button("删除",()=>Run(()=>undo.Delete<ExerciseSet>(set.Id))));}row.Children.Add(Ui.Button("＋ 记录一组",()=>EditSet(new ExerciseSet{ExerciseId=e.Id,SetNumber=data.ExerciseSets.Where(x=>x.ExerciseId==e.Id).Select(x=>x.SetNumber).DefaultIfEmpty(0).Max()+1})));}}
  }
  var history=Ui.Card(PageContent,"训练历史");foreach(var old in data.Workouts.OrderByDescending(x=>x.Date).Take(14))history.Children.Add(Ui.Button($"{old.Date:yyyy-MM-dd} · {old.Title}",async()=>await Navigate(PageId.Fitness,old.Date)));
 }
 async void EditWorkout(Workout item){if(!await StartEditor("训练安排"))return;var name=Ui.Field(DrawerContent,"训练主题",item.Title);var date=Ui.Field(DrawerContent,"日期",item.Date.ToString("yyyy-MM-dd"));var time=Ui.Field(DrawerContent,"开始时间 HH:mm（可留空）",item.StartTime?.ToString("HH:mm")??"");var minutes=Ui.Field(DrawerContent,"预计分钟（可留空）",item.PlannedMinutes?.ToString()??"");var rest=Ui.Choice(DrawerContent,"当天安排",["训练日","休息日"],item.IsRestDay?1:0);Observe("workout-"+item.Id,()=>{var d=item with{Title=name.Text,Date=Ui.Date(date.Text),StartTime=Ui.Time(time.Text),PlannedMinutes=Ui.OptionalNumber(minutes.Text,"分钟"),IsRestDay=rest.SelectedIndex==1};Validation.Workout(d);return()=>new FitnessService(store).Save(d);},name,date,time,minutes,rest);FinishEditor();}
 async void EditExercise(Exercise item)
 {
  if(!await StartEditor("训练动作"))return;var name=Ui.Field(DrawerContent,"动作名称",item.Name);var kind=Ui.Choice(DrawerContent,"记录方式",["力量：组数 / 次数 / 重量","有氧：按分钟记录"],item.Kind=="duration"?1:0);var order=Ui.Field(DrawerContent,"显示顺序（从0开始）",item.SortOrder.ToString());var strength=new StackPanel();DrawerContent.Children.Add(strength);var sets=Ui.Field(strength,"计划组数",item.PlannedSets?.ToString()??"");var reps=Ui.Field(strength,"计划每组次数",item.PlannedReps?.ToString()??"");var weight=Ui.Field(strength,"计划重量 kg（可留空）",item.PlannedWeightKg?.ToString()??"");var duration=new StackPanel();DrawerContent.Children.Add(duration);var plan=Ui.Field(duration,"计划分钟",item.PlannedMinutes?.ToString()??"");var actual=Ui.Field(duration,"实际分钟（可留空）",item.ActualMinutes?.ToString()??"");void Visibility(){strength.Visibility=kind.SelectedIndex==0?System.Windows.Visibility.Visible:System.Windows.Visibility.Collapsed;duration.Visibility=kind.SelectedIndex==1?System.Windows.Visibility.Visible:System.Windows.Visibility.Collapsed;}kind.SelectionChanged+=(_,_)=>Visibility();Visibility();
  Observe("exercise-"+item.Id,()=>{var isStrength=kind.SelectedIndex==0;var d=item with{Name=name.Text,Kind=isStrength?"strength":"duration",SortOrder=Ui.Number(order.Text,"顺序"),PlannedSets=isStrength?Ui.OptionalNumber(sets.Text,"组数"):null,PlannedReps=isStrength?Ui.OptionalNumber(reps.Text,"次数"):null,PlannedWeightKg=isStrength?Ui.Weight(weight.Text):null,PlannedMinutes=!isStrength?Ui.OptionalNumber(plan.Text,"计划分钟"):null,ActualMinutes=!isStrength?Ui.OptionalNumber(actual.Text,"实际分钟"):null};Validation.Exercise(d);return()=>new FitnessService(store).Save(d);},name,kind,order,sets,reps,weight,plan,actual);FinishEditor();
 }
 async void EditSet(ExerciseSet item){if(!await StartEditor("实际完成一组"))return;var number=Ui.Field(DrawerContent,"组号",item.SetNumber.ToString());var reps=Ui.Field(DrawerContent,"实际次数",item.ActualReps.ToString());var weight=Ui.Field(DrawerContent,"实际重量 kg（可留空）",item.ActualWeightKg?.ToString()??"");Observe("set-"+item.Id,()=>{var d=item with{SetNumber=Ui.Number(number.Text,"组号"),ActualReps=Ui.Number(reps.Text,"次数"),ActualWeightKg=Ui.Weight(weight.Text)};Validation.Set(d);return()=>new FitnessService(store).Save(d);},number,reps,weight);FinishEditor();}
}
