using System.Text.Json;
using System.Text.Json.Nodes;
using Microsoft.Data.Sqlite;
using PersonalLife.Core;
namespace PersonalLife.Tests;
[TestClass]public class BackupTests
{
 static AppSnapshot Full(){var d=new DateOnly(2026,9,13);var w=new Workout{Date=d,Title="训练"};var e=new Exercise{WorkoutId=w.Id,Name="深蹲",PlannedSets=3,PlannedReps=10};return new(){Tasks=[new(){Date=d,Title="事项"}],Workouts=[w],Exercises=[e],ExerciseSets=[new(){ExerciseId=e.Id,SetNumber=1,ActualReps=10}],Meals=[new(){Date=d,PlannedText="鸡蛋",ActualText="鸡蛋",IsRecorded=true}],WaterEntries=[new(){Date=d.AddDays(-1),Milliliters=300}],GamePlans=[new(){Date=d,GameName="星露谷",PlannedMinutes=60}],GameSessions=[new(){Date=d,GameName="星露谷",DurationMinutes=30}],Journals=[new(){Date=d,Summary="日记",UpdatedAt=DateTimeOffset.Now}],Settings=new(){WeekStartsOn="sunday"}};}
 [TestMethod]public void RoundTripAllEntities(){using var t=new TestStore();var b=new BackupService(t.Store);var data=Full();t.Store.ReplaceAll(data);var p=Path.Combine(t.Folder,"backup.json");b.Export(p);var preview=b.Preview(p);b.Clear();Assert.IsEmpty(t.Store.ReadAll().Entities());b.Restore(preview);Assert.AreEqual(JsonSerializer.Serialize(data),JsonSerializer.Serialize(t.Store.ReadAll()));}
 [TestMethod]public void CorruptAndUnsupportedDoNotModify(){using var t=new TestStore();t.Store.ReplaceAll(Full());var b=new BackupService(t.Store);var p=Path.Combine(t.Folder,"b.json");var before=JsonSerializer.Serialize(t.Store.ReadAll());File.WriteAllText(p,"broken");Assert.Throws<Exception>(()=>b.Preview(p));b.Export(p);var root=JsonNode.Parse(File.ReadAllText(p))!;root["formatVersion"]=999;File.WriteAllText(p,root.ToJsonString());Assert.Throws<Exception>(()=>b.Preview(p));Assert.AreEqual(before,JsonSerializer.Serialize(t.Store.ReadAll()));}
 [TestMethod]public void MissingArraysAndDuplicateIdsRejected(){using var t=new TestStore();t.Store.ReplaceAll(Full());var b=new BackupService(t.Store);var p=Path.Combine(t.Folder,"b.json");b.Export(p);var root=JsonNode.Parse(File.ReadAllText(p))!;root["data"]!.AsObject().Remove("meals");File.WriteAllText(p,root.ToJsonString());Assert.Throws<Exception>(()=>b.Preview(p));b.Export(p);root=JsonNode.Parse(File.ReadAllText(p))!;var a=root["data"]!["tasks"]!.AsArray();a.Add(a[0]!.DeepClone());File.WriteAllText(p,root.ToJsonString());Assert.Throws<Exception>(()=>b.Preview(p));}
 [TestMethod]public void InvalidParentAndDurationRejected(){using var t=new TestStore();t.Store.ReplaceAll(Full());var b=new BackupService(t.Store);var p=Path.Combine(t.Folder,"b.json");b.Export(p);var r=JsonNode.Parse(File.ReadAllText(p))!;r["data"]!["exercises"]![0]!["workoutId"]=Guid.NewGuid().ToString();File.WriteAllText(p,r.ToJsonString());Assert.Throws<Exception>(()=>b.Preview(p));b.Export(p);r=JsonNode.Parse(File.ReadAllText(p))!;r["data"]!["gameSessions"]![0]!["durationMinutes"]=-1;File.WriteAllText(p,r.ToJsonString());Assert.Throws<Exception>(()=>b.Preview(p));}
 [TestMethod]public void PreviewDoesNotModifyDatabase(){using var t=new TestStore();t.Store.ReplaceAll(Full());var b=new BackupService(t.Store);var p=Path.Combine(t.Folder,"b.json");b.Export(p);t.Store.Upsert(new DailyTask{Title="保留新数据"});var before=JsonSerializer.Serialize(t.Store.ReadAll());b.Preview(p);Assert.AreEqual(before,JsonSerializer.Serialize(t.Store.ReadAll()));}
 [TestMethod]public void FailureMidRestoreRollsBackEverything(){using var t=new TestStore();t.Store.ReplaceAll(Full());var b=new BackupService(t.Store);var p=Path.Combine(t.Folder,"b.json");b.Export(p);var preview=b.Preview(p);t.Store.Upsert(new DailyTask{Title="恢复前新数据"});var before=JsonSerializer.Serialize(t.Store.ReadAll());using(var c=new SqliteConnection($"Data Source={t.PathName};Pooling=False")){c.Open();using var cmd=c.CreateCommand();cmd.CommandText="CREATE TRIGGER fail_restore BEFORE INSERT ON game_sessions BEGIN SELECT RAISE(ABORT, 'injected disk write failure'); END";cmd.ExecuteNonQuery();}Assert.Throws<Exception>(()=>b.Restore(preview));Assert.AreEqual(before,JsonSerializer.Serialize(t.Store.ReadAll()));}
 [TestMethod]public void ClearLeavesExternalBackup(){using var t=new TestStore();t.Store.ReplaceAll(Full());var b=new BackupService(t.Store);var p=Path.Combine(t.Folder,"b.json");b.Export(p);var saved=File.ReadAllText(p);b.Clear();Assert.AreEqual(saved,File.ReadAllText(p));Assert.AreEqual("monday",t.Store.ReadAll().Settings.WeekStartsOn);}
 [TestMethod]public void ExportFailureDoesNotDestroyOldTarget(){using var t=new TestStore();var b=new BackupService(t.Store);var p=Path.Combine(t.Folder,"b.json");File.WriteAllText(p,"keep");using(var locked=new FileStream(p,FileMode.Open,FileAccess.ReadWrite,FileShare.None)){Assert.Throws<Exception>(()=>b.Export(p));}Assert.AreEqual("keep",File.ReadAllText(p));}
}
