using System.Windows;
using System.Windows.Controls;
using System.Windows.Automation;
using System.Windows.Media;
using PersonalLife.App;
namespace PersonalLife.Tests;
[TestClass][DoNotParallelize]
public class DesktopUiTests
{
 [TestMethod]public void CurrentNavigationRemainsVisiblySelected()=>Sta.Run(async()=>{using var t=new TestStore();var w=new MainWindow(t.Folder);try{w.Show();var nav=(StackPanel)w.FindName("Navigation");((Button)nav.Children[2]).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Task.Delay(30);Assert.AreNotEqual(((Button)nav.Children[0]).FontWeight,((Button)nav.Children[2]).FontWeight);}finally{var closed=new TaskCompletionSource();w.Closed+=(_,_)=>closed.SetResult();w.Close();await closed.Task.WaitAsync(TimeSpan.FromSeconds(5));}});
 static async Task Until(Func<bool> predicate){var deadline=DateTime.UtcNow.AddSeconds(5);while(!predicate()){if(DateTime.UtcNow>=deadline)throw new TimeoutException("界面状态未在5秒内更新");await Task.Delay(20);}}
 [TestMethod]public void SuccessfulDeleteRetryRefreshesVisibleList()=>Sta.Run(async()=>{using var t=new TestStore();t.Store.Upsert(new PersonalLife.Core.DailyTask{Date=DateOnly.FromDateTime(DateTime.Now),Title="不能复活"});void Sql(string sql){using var c=new Microsoft.Data.Sqlite.SqliteConnection($"Data Source={t.PathName};Pooling=False");c.Open();using var cmd=c.CreateCommand();cmd.CommandText=sql;cmd.ExecuteNonQuery();}Sql("CREATE TRIGGER fail_delete BEFORE DELETE ON daily_tasks BEGIN SELECT RAISE(ABORT,'injected failure'); END");var w=new MainWindow(t.Folder);try{w.Show();var nav=(StackPanel)w.FindName("Navigation");((Button)nav.Children[1]).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Task.Delay(40);w.UpdateLayout();Find<Button>(w).Single(b=>Equals(b.Content,"删除")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Until(()=>((TextBlock)w.FindName("SaveLabel")).Text.StartsWith("保存失败"));Sql("DROP TRIGGER fail_delete");((Button)w.FindName("RetryButton")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Until(()=>((TextBlock)w.FindName("SaveLabel")).Text=="已保存");w.UpdateLayout();Assert.IsEmpty(t.Store.ReadAll().Tasks);Assert.IsFalse(Find<CheckBox>(w).Any(x=>x.Content?.ToString()?.Contains("不能复活")==true));}finally{var closed=new TaskCompletionSource();w.Closed+=(_,_)=>closed.SetResult();w.Close();await closed.Task.WaitAsync(TimeSpan.FromSeconds(5));}});
 [TestMethod]public void OpeningWaterEditorThenDiscardKeepsMealDraft()=>Sta.Run(async()=>{using var t=new TestStore();var w=new MainWindow(t.Folder);try{w.Show();var nav=(StackPanel)w.FindName("Navigation");((Button)nav.Children[3]).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Task.Delay(30);w.UpdateLayout();Find<TextBox>(w).First(x=>AutomationProperties.GetName(x)=="计划吃什么").Text="刚输入的早餐";Find<Button>(w).Single(x=>Equals(x.Content,"自定义饮水")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Task.Delay(80);w.UpdateLayout();Find<Button>(w).Single(x=>Equals(x.Content,"放弃尚未保存的修改")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Task.Delay(80);Assert.AreEqual("刚输入的早餐",t.Store.ReadAll().Meals.Single(x=>x.Slot=="breakfast").PlannedText);}finally{var closed=new TaskCompletionSource();w.Closed+=(_,_)=>closed.SetResult();w.Close();await closed.Task.WaitAsync(TimeSpan.FromSeconds(5));}});
 [TestMethod]public void AllPagesRenderRealDataAtDesktopSizes()=>Sta.Run(async()=>{using var t=new TestStore();t.Store.ReplaceAll(SampleData.Create(DateOnly.FromDateTime(DateTime.Now)));var w=new MainWindow(t.Folder){ShowActivated=false};try{w.Show();var nav=(StackPanel)w.FindName("Navigation");var titles=new[]{"首页总览","今日计划","健身计划","饮食计划","游戏娱乐","总结日志","数据与设置"};for(int i=0;i<7;i++){((Button)nav.Children[i]).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Task.Delay(35);w.UpdateLayout();Assert.AreEqual(titles[i],((TextBlock)w.FindName("PageTitle")).Text);Assert.IsGreaterThan(10,Find<TextBlock>(w).Count());Capture(w,"page-"+i);}w.Width=900;w.Height=650;((Button)nav.Children[0]).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Task.Delay(35);w.UpdateLayout();Assert.IsLessThanOrEqualTo(900,w.ActualWidth);Capture(w,"home-small");}finally{var closed=new TaskCompletionSource();w.Closed+=(_,_)=>closed.SetResult();w.Close();await closed.Task.WaitAsync(TimeSpan.FromSeconds(5));}});
 static void Capture(MainWindow window,string name){var folder=Environment.GetEnvironmentVariable("PERSONAL_LIFE_EVIDENCE_DIR");if(string.IsNullOrWhiteSpace(folder))return;Directory.CreateDirectory(folder);var bitmap=new System.Windows.Media.Imaging.RenderTargetBitmap((int)Math.Ceiling(window.ActualWidth),(int)Math.Ceiling(window.ActualHeight),96,96,PixelFormats.Pbgra32);bitmap.Render(window);var encoder=new System.Windows.Media.Imaging.PngBitmapEncoder();encoder.Frames.Add(System.Windows.Media.Imaging.BitmapFrame.Create(bitmap));using var file=File.Create(Path.Combine(folder,name+".png"));encoder.Save(file);}
 [TestMethod]public void CloseFlushesNewTaskToDisk()=>Sta.Run(async()=>{using var t=new TestStore();var w=new MainWindow(t.Folder);w.Show();var nav=(StackPanel)w.FindName("Navigation");((Button)nav.Children[1]).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Task.Delay(40);w.UpdateLayout();Find<Button>(w).Single(b=>Equals(b.Content,"＋ 添加事项")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));w.UpdateLayout();Find<TextBox>(w).Single(x=>AutomationProperties.GetName(x)=="事项名称").Text="关闭前立即保存";var closed=new TaskCompletionSource();w.Closed+=(_,_)=>closed.SetResult();w.Close();await closed.Task.WaitAsync(TimeSpan.FromSeconds(5));Assert.AreEqual("关闭前立即保存",t.Store.ReadAll().Tasks.Single().Title);});
 [TestMethod]public void DrawerDisablesUnderlyingPage()=>Sta.Run(async()=>{using var t=new TestStore();var w=new MainWindow(t.Folder);try{w.Show();var nav=(StackPanel)w.FindName("Navigation");((Button)nav.Children[1]).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Task.Delay(40);w.UpdateLayout();var add=Find<Button>(w).Single(b=>Equals(b.Content,"＋ 添加事项"));add.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Assert.IsFalse(add.IsEnabled);}finally{w.Close();}});
 static IEnumerable<T> Find<T>(DependencyObject root) where T:DependencyObject {if(root is T t)yield return t;for(int i=0;i<VisualTreeHelper.GetChildrenCount(root);i++)foreach(var child in Find<T>(VisualTreeHelper.GetChild(root,i)))yield return child;}
 [TestMethod]public void NavigationResetsScrollPosition()=>Sta.Run(async()=>{using var t=new TestStore();var w=new MainWindow(t.Folder);try{w.Show();await w.Dispatcher.InvokeAsync(()=>{});var buttons=(StackPanel)w.FindName("Navigation");((Button)buttons.Children[3]).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Task.Delay(40);w.UpdateLayout();var scroll=Find<ScrollViewer>((Panel)w.Content).First(x=>x.Content is StackPanel p&&p.Name=="PageContent");scroll.ScrollToEnd();w.UpdateLayout();Assert.IsGreaterThan(0,scroll.VerticalOffset);((Button)buttons.Children[0]).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Task.Delay(40);w.UpdateLayout();Assert.AreEqual(0,scroll.VerticalOffset);}finally{w.Close();}});
 [TestMethod]public void TaskEditorHasAccessibleNamedInput()=>Sta.Run(async()=>{using var t=new TestStore();var w=new MainWindow(t.Folder);try{w.Show();var nav=(StackPanel)w.FindName("Navigation");((Button)nav.Children[1]).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Task.Delay(40);w.UpdateLayout();var add=Find<Button>(w).Single(b=>Equals(b.Content,"＋ 添加事项"));add.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));w.UpdateLayout();Assert.IsTrue(Find<TextBox>(w).Any(x=>AutomationProperties.GetName(x)=="事项名称"));}finally{w.Close();}});
}
