using System.Diagnostics;
using System.Text.Json;
using PersonalLife.Core;
namespace PersonalLife.Tests;
[TestClass][DoNotParallelize]
public class PublishedAppTests
{
 static string Root(){var d=new DirectoryInfo(AppContext.BaseDirectory);while(d!=null&&!File.Exists(Path.Combine(d.FullName,"PRD.md")))d=d.Parent;return d?.FullName??throw new DirectoryNotFoundException("找不到工作根目录");}
 static string PublishDir=>Path.Combine(Root(),"artifacts","PersonalLife-win-x64");
 [TestMethod]public async Task ReplacingProgramInChinesePathPreservesSeparateData(){using var t=new TestStore();var original=SampleData.Create(DateOnly.FromDateTime(DateTime.Now));t.Store.ReplaceAll(original);var program=Path.Combine(t.Folder,"我的 程序");Directory.CreateDirectory(program);for(var version=0;version<2;version++){foreach(var source in Directory.GetFiles(PublishDir,"*",SearchOption.AllDirectories)){var target=Path.Combine(program,Path.GetRelativePath(PublishDir,source));Directory.CreateDirectory(Path.GetDirectoryName(target)!);File.Copy(source,target,true);File.SetAttributes(target,FileAttributes.Normal);}using var p=Process.Start(new ProcessStartInfo(Path.Combine(program,"PersonalLife.exe")){UseShellExecute=false,ArgumentList={"--data-dir",t.Folder},WindowStyle=ProcessWindowStyle.Hidden})!;try{var deadline=DateTime.UtcNow.AddSeconds(15);while(!p.HasExited&&p.MainWindowHandle==IntPtr.Zero&&DateTime.UtcNow<deadline){await Task.Delay(100);p.Refresh();}Assert.IsFalse(p.HasExited);Assert.AreNotEqual(IntPtr.Zero,p.MainWindowHandle);Assert.AreEqual(JsonSerializer.Serialize(original),JsonSerializer.Serialize(t.Store.ReadAll()));Assert.IsEmpty(Directory.GetFiles(program,"*.db",SearchOption.AllDirectories));}finally{if(!p.HasExited){p.Kill();await p.WaitForExitAsync();await Task.Delay(500);}}}}
 [TestMethod]public void PackageContainsRuntimeAndNoUserData(){Assert.IsTrue(File.Exists(Path.Combine(PublishDir,"PersonalLife.exe")),"请先运行发布命令");Assert.IsTrue(File.Exists(Path.Combine(PublishDir,"e_sqlite3.dll")));using var doc=JsonDocument.Parse(File.ReadAllText(Path.Combine(PublishDir,"PersonalLife.runtimeconfig.json")));Assert.IsTrue(doc.RootElement.GetProperty("runtimeOptions").TryGetProperty("includedFrameworks",out _),"发布包必须携带运行时");Assert.IsEmpty(Directory.GetFiles(PublishDir,"*.db",SearchOption.AllDirectories));}
 [TestMethod]public async Task PublishedProcessReopensDataAfterTermination(){using var t=new TestStore();var original=SampleData.Create(DateOnly.FromDateTime(DateTime.Now));t.Store.ReplaceAll(original);for(int i=0;i<2;i++){using var p=Process.Start(new ProcessStartInfo(Path.Combine(PublishDir,"PersonalLife.exe")){UseShellExecute=false,ArgumentList={"--data-dir",t.Folder},WindowStyle=ProcessWindowStyle.Hidden})??throw new InvalidOperationException("无法启动发布程序");try{var deadline=DateTime.UtcNow.AddSeconds(15);while(p.MainWindowHandle==IntPtr.Zero&&!p.HasExited&&DateTime.UtcNow<deadline){await Task.Delay(100);p.Refresh();}Assert.IsFalse(p.HasExited,"发布程序启动时退出");Assert.AreNotEqual(IntPtr.Zero,p.MainWindowHandle,"未打开独立桌面窗口");Assert.AreEqual(JsonSerializer.Serialize(original),JsonSerializer.Serialize(t.Store.ReadAll()));}finally{if(!p.HasExited){p.Kill();await p.WaitForExitAsync();await Task.Delay(500);}}}Assert.AreEqual(JsonSerializer.Serialize(original),JsonSerializer.Serialize(t.Store.ReadAll()));}
}
