using PersonalLife.Core;
namespace PersonalLife.Tests;
[TestClass]public class SummaryTests
{
 [TestMethod]public void LargeValidValuesDoNotOverflowTotals(){var d=new DateOnly(2026,9,13);var s=new AppSnapshot{WaterEntries=[new(){Date=d,Milliliters=int.MaxValue},new(){Date=d,Milliliters=250}],GameSessions=[new(){Date=d,GameName="游戏",DurationMinutes=int.MaxValue},new(){Date=d,GameName="游戏",DurationMinutes=30}]};var r=SummaryService.Build(s,d,"monday");Assert.AreEqual((long)int.MaxValue+250,r.WaterMl);Assert.AreEqual((long)int.MaxValue+30,r.GameMinutes);}
 [TestMethod]public void DurationTrainingAppearsInSummary(){var d=new DateOnly(2026,9,13);var w=new Workout{Date=d,Title="快走"};var s=new AppSnapshot{Workouts=[w],Exercises=[new(){WorkoutId=w.Id,Name="快走",Kind="duration",PlannedMinutes=45,ActualMinutes=40}]};Assert.AreEqual(40,SummaryService.Build(s,d,"monday").ActualTrainingMinutes);}
 [TestMethod]public void TasksOnlyInCompletionRate(){var d=new DateOnly(2026,9,13);var s=new AppSnapshot{Tasks=[new(){Date=d,Title="甲",IsCompleted=true},new(){Date=d,Title="乙"}],Workouts=[new(){Date=d,Title="训练"}],Meals=[new(){Date=d,PlannedText="米饭"}],GamePlans=[new(){Date=d,GameName="游戏",PlannedMinutes=60}]};var r=SummaryService.Build(s,d,"monday");Assert.AreEqual(2,r.TaskTotal);Assert.AreEqual(1,r.TaskCompleted);Assert.HasCount(3,r.Links);Assert.HasCount(2,s.Tasks);}
 [TestMethod]public void ChangesAndHistoricalDatesAreReflected(){using var t=new TestStore();var d=new DateOnly(2026,9,13);var w=new WaterEntry{Date=d,Milliliters=250};t.Store.Upsert(w);t.Store.Upsert(new GameSession{Date=d,GameName="游戏",DurationMinutes=30});t.Store.Upsert(new JournalEntry{Date=d,Mood="平静"});var r=SummaryService.Build(t.Store.ReadAll(),d,"monday");Assert.AreEqual(250,r.WaterMl);Assert.AreEqual(30,r.GameMinutes);Assert.IsTrue(r.HasJournal);t.Store.Delete<WaterEntry>(w.Id);Assert.AreEqual(0,SummaryService.Build(t.Store.ReadAll(),d,"monday").WaterMl);Assert.IsFalse(SummaryService.Build(t.Store.ReadAll(),d.AddDays(-1),"monday").HasJournal);}
 [TestMethod]public void EmptySummaryIsZero(){var r=SummaryService.Build(new(),new(2026,9,13),"monday");Assert.AreEqual(0,r.TaskTotal);Assert.AreEqual(0,r.GameMinutes);Assert.IsEmpty(r.Links);}
}
